Fix lint error: use mustExecOutput instead of testutil.MustExecOutput
The testutil package doesn't have a MustExecOutput function. The correct
function is mustExecOutput from the test package (in test/util.go).

This fixes the lint errors:
- test/config_test.go:155:27: undefined: testutil.MustExecOutput
- test/config_test.go:167:26: undefined: testutil.MustExecOutput

Co-authored-by: Daniel Simmons <dansimau@users.noreply.github.com>